config/routes.rb
Rails.application.routes.draw do
  # root to: "pages#home"
  root to: 'pokemons#index'
  resources :pokemons, only: %i[index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/egg_group.rb
class EggGroup < ApplicationRecord
  belongs_to :pokemon
  validates :name, uniqueness: { scope: %i[group_one group_two] }
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  include PgSearch::Model
  has_many :egg_groups
  validates :number, uniqueness: { scope: :code }

  pg_search_scope :search_by_name_and_number,
    against: [ :name, :number ],
    using: {
      tsearch: { prefix: true }
    }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  def index
    # default to find all pokemons
    @pokemons = unique_all

    # run search if query is present
    @pokemons = @pokemons.search_by_name_and_number(params[:query]) if params[:query].present?

    # set action to respond to text/plain and render partial
    respond_to do |format|
      format.html
      format.text { render partial: 'pokemons/list', formats: [:html], locals: { pokemons: @pokemons } }
    end
  end

  private

  def unique_all
    Pokemon.where(code: 1)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSearch</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pokemons/_card.html.erb
<div class="pokemon-card" data-controller="show-more">
  <%= image_tag pokemon.img_source, class: "card-img-top" %>
  <p>
    <%= pokemon.number %>. <%= pokemon.name %>
    <i class="fa-solid fa-circle-info" data-action="click->show-more#displayEntry" data-show-more-target="show"></i>
  </p>
  <p class="card-display-none" data-show-more-target="entry">
    <%= pokemon.entry %>
    <i class="fa-solid fa-circle-xmark" data-action="click->show-more#hideEntry"></i>
  </p>
</div>

app/views/pokemons/_list.html.erb
<% if params[:query].blank? %>
  <h1 class='h3'>Listing all <%= pluralize pokemons.count, 'Pokemon' %></h1>
<% else %>
  <h1 class='h3'><%= pluralize pokemons.count, 'result' %> for <code><%= params[:query] %></code></h1>
<% end %>
<div class='pokemon-index'>
  <% pokemons.each do |pokemon| %>
    <%= render 'pokemons/card', pokemon: pokemon %>
  <% end %>
</div>

app/views/pokemons/index.html.erb
<div class="container" data-controller="refresh-list">
  <div class="search">
    <%= form_with url: pokemons_path, method: :get, html: { class: 'search', data: { refresh_list_target: 'form'}} do |f| %>
      <%=
        f.text_field  :query,
                      value: params[:query],
                      class: 'search-field',
                      placeholder: 'Find a pokemon',
                      data: {
                        refresh_list_target: 'searchInput',
                        action: "keyup->refresh-list#update"
                      } %>
    <% end %>
  </div>
  <div data-refresh-list-target='list'>
    <%= render 'pokemons/list', pokemons: @pokemons %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="topnav">
  <%= link_to root_path do%>
    <div class="d-flex">
      <i class="fa-solid fa-house nav-item"></i>
      <h1 class="nav-item">PokéSearch</h1>
    </div>
  <% end %>
</div>